services:
  lc-incubator-frontend:
    container_name: lc-incubator-${ENVIRONMENT}
    image: ghcr.io/ut-bms-ist/lc-incubator-frontend:${LC_INCUBATOR_TAG:-latest}
    ports:
      - ${FRONTEND_PORT}:80
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
